### ISSUE TITLE
Private key routines:PEM_read_bio:no start line

### ISSUE THREAD

**Issue by Ronnyrr** [DanielHuisman/node-tikkie#1]
Hi,

I'm trying to use your Node wrapper for Tikkie, but can't load the private key. I tried creating a `.key` file containing a string of my client secret. I also tried many variations on this, but keep getting the error `routines:PEM_read_bio:no start line`. How to load this properly? Do you have an example of how to do it? 

Thanks in advance ;)

**Comment by DanielHuisman** [comment]
Assuming your private key is `private.pem` in RSA format (the file should start with `-----BEGIN RSA PRIVATE KEY-----`).

```javascript
const config = new TikkieConfig(apiKey, useSandbox);
config.loadPrivateKey('private.pem', 'RS256');
```

If you don't specify a absolute path, Node.js will resolve the `private.pem` file in the current working directory. If you want the path to always be relative to the source directory, use:

```javascript
import path from 'path';

const config = new TikkieConfig(apiKey, useSandbox);
config.loadPrivateKey(path.join(__dirname, 'private.pem'), 'RS256');
```

Hope this helps!

**Comment by Ronnyrr** [comment]
Thanks for your reply. I'm assuming the Consumer Secret from the Tikkie APU it the expected private key? Any tips on how to create a `.pem` file from that secret?

**Comment by DanielHuisman** [comment]
The documentation of the Tikkie API explains how to generate a public/private key pair. Go to the "Getting Started" page (https://developer.abnamro.com/get-started#authentication) and look under "Create public/private key pair".

**Comment by Ronnyrr** [comment]
Thanks for the help and pointing out this auth method. Completely missed that.
